#

In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# to find and drop the missing values from the given dataset
import pandas as pd
# World alcohol consumption data
w_a_con = pd.read_csv('/kaggle/input/iml-data/alphabet_stock_data.csv')
print("World alcohol consumption sample data:")
print(w_a_con.head())
print("\nMissing values:")
print(w_a_con.isnull())
print("\nDropping the missing values:")
print(w_a_con.dropna())

In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# to remove the duplicates from the given dataset
import pandas as pd
data = { "name": ["Jal", "Dhruvi", "Kinjal", "Bagthariya", "Jal"], "age": [82, 90, 91, 80, 82] }
df = pd.DataFrame(data)
newdf = df.drop_duplicates()
print(df)
print()
print(newdf)