In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# Write a Pandas program to implement following operation
# to convert a NumPy array to a Pandas series

import numpy as np
import pandas as pd
array = np.array([1, 2,3, 4, 5, 6, 7, 8])
print("Numpy array:- ",array)
series = pd.Series(array)
print("Pandas Series : \n",series)

In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# Write a Pandas program to implement following operation
# to convert the first column of a DataFrame as a Series

import numpy as np
import pandas as pd 
a = pd.DataFrame() 
print(a)
a = pd.DataFrame({'A':[11,12,13],'B':[14,15,16],}) 
print("Dataframe:")
print(a)

In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# Write a Pandas program to implement following operation
# to create the mean and standard deviation of the data of a given Series

import numpy as np
import pandas as pd
s = pd.Series(data = [1, 2, 3,4, 5, 6, 7, 8])
print(s)

In [ ]:
# Name:- Majithiya Jal
# Enrollment NO.:- 216270307082
# Write a Pandas program to implement following operation
# to sort a given Series
import pandas as pd
import numpy as np
sr = pd.Series([45,87,32,10,0])
print(sr)
print(sr.sort_values(ascending=True))